resources:
  - ../../namespace.yaml
  - ../../configmap-reg-adapter.yaml
  - ../../secret-reg-credentials.yaml
  - ../../deployment-reg-adapter.yaml
  - ../../deployment-reg-worker.yaml
  - ../../service-and-monitor.yaml
  - ../../hpa-reg-worker.yaml
  - ../../pdb-reg-adapter.yaml

patches:
  - target:
      kind: Deployment
      name: reg-adapter
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: reg-adapter
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: reg-adapter
                resources:
                  requests:
                    cpu: "500m"
                    memory: "512Mi"
                  limits:
                    cpu: "1"
                    memory: "1Gi"

  - target:
      kind: Deployment
      name: reg-adapter-worker
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: reg-adapter-worker
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: reg-adapter-worker
                resources:
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
                  limits:
                    cpu: "2"
                    memory: "2Gi"

