apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reg-adapter-pdb
  namespace: reg-adapter
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reg-adapter

