apiVersion: v1
kind: Service
metadata:
  name: reg-adapter
  namespace: reg-adapter
  labels:
    app.kubernetes.io/name: reg-adapter
spec:
  selector:
    app.kubernetes.io/name: reg-adapter
  ports:
    - name: http
      port: 80
      targetPort: 8080


