apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reg-adapter-monitor
  namespace: reg-adapter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reg-adapter
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

