apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reg-adapter.fullname" . }}
  labels:
    {{- include "reg-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reg-adapter.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reg-adapter.fullname" . }}
    spec:
      containers:
        - name: reg-adapter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CONFIG_PATH
              value: "/etc/reg-adapter/config/mappings.yaml"
            - name: REGU_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secret.create }}{{ include "reg-adapter.fullname" . }}-secret{{ else }}{{ .Values.secret.name }}{{ end }}
                  key: username
            - name: REGU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secret.create }}{{ include "reg-adapter.fullname" . }}-secret{{ else }}{{ .Values.secret.name }}{{ end }}
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/reg-adapter/config
              readOnly: true
          resources:
{{ toYaml .Values.resources.adapter | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: config
          configMap:
            name: {{ include "reg-adapter.fullname" . }}-config

