apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "reg-adapter.fullname" . }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reg-adapter.fullname" . }}

