apiVersion: v1
kind: Service
metadata:
  name: {{ include "reg-adapter.fullname" . }}
  labels:
    {{- include "reg-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "reg-adapter.fullname" . }}


{{- if .Values.prometheus.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "reg-adapter.fullname" . }}-sm
  labels:
    {{- include "reg-adapter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reg-adapter.fullname" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}

